# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desig',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tocayoapp.Token'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
