# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0002_auto_20151206_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea',
            field=models.CharField(max_length=47, unique=True),
        ),
        migrations.AlterField(
            model_name='lang',
            name='long',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='lang',
            name='name',
            field=models.CharField(max_length=47, unique=True),
        ),
        migrations.AlterField(
            model_name='lang',
            name='short',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='scopetype',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='utter',
            name='utter',
            field=models.CharField(max_length=47, unique=True),
        ),
    ]
