# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0005_auto_20151210_0452'),
    ]

    operations = [
        migrations.RenameField('Author', 'author', 'name'),
        migrations.RenameField('Utter', 'utter', 'name'),
        migrations.RenameField('Idea', 'idea', 'name'),
    ]
