# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0007_gender_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='description',
            field=models.CharField(max_length=15),
        ),
    ]
