# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0009_auto_20151213_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onto',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onto_child_of', to='tocayoapp.Idea'),
        ),
    ]
