# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0011_auto_20151215_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tocayoapp.Author')),
            ],
        ),
    ]
