# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocayoapp', '0012_reltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_core_set', to='tocayoapp.Desig')),
                ('relType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tocayoapp.RelType')),
                ('satellite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_satellite_set', to='tocayoapp.Desig')),
            ],
        ),
    ]
